version: '3.8'
services:

  digitalai-release:
    build: digitalai-release
    ports:
      - 5516:5516
    environment:
      - ADMIN_PASSWORD=admin
      - ACCEPT_EULA=Y
      - SERVER_URL=http://host.docker.internal:5516
    user: root  # Needed for docker runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Needed for docker runner

  digitalai-release-setup:
    build: digitalai-release-setup
    depends_on:
      - digitalai-release
    command: ["apply", "-v", "-f", "/data/docker-runner.yaml"]
    volumes:
      - ./digitalai-release-setup:/data:ro

  container-registry:
    image: registry:2
    ports:
      - 5050:5000
    volumes:
      - .:/var/lib/registry

  container-registry-ui:
    image: parabuzzle/craneoperator:latest
    ports:
      - 8086:80
    environment:
      - REGISTRY_HOST=container-registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - REGISTRY_ALLOW_DELETE=true
      - SSL_VERIFY=false
      - TITLE=Digital.ai Release Docker Registry
    depends_on:
      - container-registry

  localstack:
#    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
#      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"